In [48]:
import  numpy as np
array1=np.array([1,2,3] , dtype=np.float64)
print(array1)
print(type(array1))
print(array1.dtype)
print(array1.shape)
print("*#"*20)
print(np.zeros((1,2)))
print(np.ones((2,2)))
print(np.full((2,2),7))

[1. 2. 3.]
<class 'numpy.ndarray'>
float64
(3,)
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
[[0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]


In [37]:
#slicing of arrays
import numpy as np
a1=np.array([[1,2,3,4],[5,6,7,8]])
print('The value of a1 is=')
print(a1)
b1=a1[:,1:3]
print("value of b1 is")
print(b1)
b1[0,0]=5
print('value of new a1 is ')
print(a1)
print('if we want to print a single row of the a1  with rank 1 then')
r_a1=a1[1,:]
print(r_a1)
print('if we want to print a single row of the a1  with rank 2 then')
r1_a1=a1[1:2,:]
print(r1_a1)
print('print items at particular index in an array ')
print(a1[[0,1],[1,1]])


The value of a1 is=
[[1 2 3 4]
 [5 6 7 8]]
value of b1 is
[[2 3]
 [6 7]]
value of new a1 is 
[[1 5 3 4]
 [5 6 7 8]]
if we want to print a single row of the a1  with rank 1 then
[5 6 7 8]
if we want to print a single row of the a1  with rank 2 then
[[5 6 7 8]]
print items at particular index in an array 
[5 6]


In [47]:
# if we want to add someting to a particular indices
print(a1)
b=np.array([0,3])
print('print items at 0 index in 1st row and ite at 3rd indx in row 2')
print(a1[np.arange(2),b])
print('checking a particular condition in a array using bool')
bool_idx=(a1%2==0)
print(bool_idx)
print(a1[bool_idx])

[[1 5 3 4]
 [5 6 7 8]]
print items at 0 index in 1st row and ite at 3rd indx in row 2
[1 8]
checking a particular condition in a array using bool
[[False False False  True]
 [False  True False  True]]
[4 6 8]


In [62]:
#arithmatic operations on numpy arrays
x=np.array([[2,4,3],[3,5,3],[1,2,3]])
y=np.array([[2,5,2],[3,4,2],[2,3,4]])
z=x.dot(y)
print('matrix multiplication')
print(z)
print('multiply elements')
w=np.multiply(x,y)
print(w)
print('the sum of items in rows of array x')
print(np.sum(x,axis=1))
print('the sum of items in column of array x')
print(np.sum(x,axis=0))
print('transpose of x is ')
print(x.T)

matrix multiplication
[[22 35 24]
 [27 44 28]
 [14 22 18]]
multiply elements
[[ 4 20  6]
 [ 9 20  6]
 [ 2  6 12]]
the sum of items in rows of array x
[ 9 11  6]
the sum of items in column of array x
[ 6 11  9]
transpose of x is 
[[2 3 1]
 [4 5 2]
 [3 3 3]]


In [76]:
#broadcasting
print(x)
v=np.array([1,2,3])
print('we have to add v to every row of x')
#vx=np.tile(v,(3,1))
xs=x+v
print(xs)
xr=np.array([[1,2,3,4],[2,3,4,5]])
print('change the shape of martrix')
print(np.reshape(xr,(4,2)))
print('it doesnt chnge  tthe actual value of the actual array ')
print(xr)

[[2 4 3]
 [3 5 3]
 [1 2 3]]
we have to add v to every row of x
[[3 6 6]
 [4 7 6]
 [2 4 6]]
change the shape of martrix
[[1 2]
 [3 4]
 [2 3]
 [4 5]]
it doesnt chnge  tthe actual value of the actual array 
[[1 2 3 4]
 [2 3 4 5]]
